#!/bin/bash
set -e

if [ $# -eq 0 ]; then
  echo "No file supplied!"
  exit 0
fi

file=$1
target=$2

if [ ! -e $file ]; then
  echo "File $file not found!"
  exit 1
fi

if [ ! -f $file ]; then
  echo "File $file is not a regular file!"
  exit 1
fi

if [[ $target ]]; then
  perl -pe 's/{{(.*?)}}/$ENV{$1}/g' "$file" > temp
  mv temp "$target"
else
  echo "Argument 2 is empty"
  exit 1
fi

exit 0